language: rust
rust:
  - stable
cache: cargo
git:
  depth: 1
jobs:
  include:
    - stage: check
      name: Tests
      script: cargo test
    - stage: check
      name : Rustfmt
      install: rustup component add rustfmt-preview
      script: cargo fmt -- --check
    - stage: check
      name: Clippy
      install: rustup component add clippy-preview
      script: cargo clippy
    - stage: build
      name: Package
      script: cargo package
    - stage: build
      name: Build w/o features
      script: cargo build
stages:
  - name: check
  - name: build
notifications:
  email: false
