[package]
name = "svc-error"
version = "0.1.0"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]
edition = "2018"

[dependencies]
http = "0.1"
serde = { version = "1.0" }
serde_derive = { version = "1.0" }
diesel = { version = "1.4", optional = true }
r2d2 = { version = "0.8", optional = true }
svc-agent = { version = "0.4", optional = true }
svc-authn = { version = "0.4", optional = true }
svc-authz = { version = "0.4", optional = true }

[features]
default = []